name: Trigger on /src/games Changes

on:
  push:
    paths:
      - 'src/games/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run game-packer script
        run: |
          # Get list of changed files in the src/games directory
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^src/games/")
          # Run game-packer with the changed files
          python src/game-packer.py "$CHANGED_FILES"