name: Run Script on /games Change

on:
  push:
    paths:
      - 'games/**'  # Only triggers if something in /games changes
    branches:
      - main  # Adjust if it's another branch

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch enough history to access HEAD^

      - name: Run Custom Script
        run: |
          modified_file=$(git diff --name-only HEAD^ HEAD | grep '^games/')
          parent_folder=$(dirname "$modified_file" | cut -d'/' -f2)
          echo "Parent folder: $parent_folder"
